#!/usr/bin/env bash

# Count the entries per century in the Common Era.

years="$(git grep -Ewoh '^- ([0-9]{1,2}) CE:' README.md)"

count=$(echo "$years" | wc -l)
echo "   0s: $count"

years="$(git grep -Ewoh '^- ([0-9]{3}) CE:' README.md)"

for century in 1 2 3 4 5 6 7 8 9; do
    count=$(echo "$years" | grep -o "^- ${century}" | wc -l)
    echo " ${century}00s: $count"
done

years="$(git grep -Ewoh '^- ([0-9]{4}) CE:' README.md)"

for century in 10 11 12 13 14 15 16 17 18 19 20; do
    count=$(echo "$years" | grep -o "^- ${century}" | wc -l)
    echo "${century}00s: $count"
done
